#!/bin/bash

set -e

mv /usr/bin/prometheus.yml /etc/prometheus/

dpkg --status openvpn &> /dev/null

if [ $? -ne 0 ]; then
	exit 0
fi

curl -sSL https://raw.githubusercontent.com/B4DCATs/openvpn_exporter/main/quick-start.sh | bash

cat << EOF >> /etc/prometheus/prometheus.yml

  - job_name: openvpn_exporter
    static_configs:
      - targets: [localhost:9176]
EOF

systemctl restart prometheus
systemctl status prometheus
